name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: sequential make
      run: cd sequential && make
    - name: sequential make run
      run: cd sequential && make run
    - name: OpenMP make
      run: cd openmp && make
    - name: OpenMP make run with 2 threads
      run: cd openmp && make run THREADS=2
